
### 
GET http://localhost:3000/users/employees/all

###
POST http://localhost:3000/users
Content-Type: application/json

{
    "email": "bilbo@shire.net",
    "firstName": "Bilbo",
    "lastName": "Baggins",
    "Occupation": "RUNNER",
    "role": "EMPLOYER",
    "password": "1234Aa!",
    "loginCode": "1234Aa!" 
}   

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "test@example.com",
    "password": "123456"
}   

###
PUT http://localhost:3000/availability/3
Content-Type: application/json

{   
    "userId": 3,
    "date": "2026-04-23",
    "shift": "AFTERNOON"
        
}

###
GET http://localhost:3000/availability/3

###
POST http://localhost:3000/create-test-user   